### ISSUE TITLE
Local copy of the DNS root zone (hyperlocal)

### ISSUE THREAD

**Issue by mibere** [jedisct1/dnscrypt-server-docker#38]
Hi Frank,

what's your opinion about adding a local copy of the DNS root zone (hyperlocal) by default?

I think it could be done by adding this to _/opt/unbound/etc/unbound/unbound.conf_ via [unbound.sh](https://github.com/jedisct1/dnscrypt-server-docker/blob/master/unbound.sh)

```
server:
  ...
  tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

auth-zone:
  name: "."
  url: "https://www.internic.net/domain/root.zone"
  fallback-enabled: yes
  for-downstream: no
  for-upstream: yes
  zonefile: "var/root.zone"
```
