### ISSUE TITLE
private addresses in unbound.conf

### ISSUE THREAD

**Issue by mibere** [jedisct1/dnscrypt-server-docker#44]
Is it necessary or a good idea to add this to _unbound.conf_?

```
server:
  ...

  # Ensure privacy of local IP ranges
  private-address: 192.168.0.0/16
  private-address: 172.16.0.0/12
  private-address: 169.254.0.0/16
  private-address: 10.0.0.0/8
  private-address: fe80::/10
  private-address: fd00::/8
```
